[tool.poetry]
name = "netcleanser"
version = "0.2.1"
description = "The library makes parsing and manipulation of URLğŸŒ and Email addressğŸ“§ easy."
readme = "README.md"
authors = [
    "Shinichi Takayanagi <shinichi.takayanagi@gmail.com>",
    "Nakamura Michihiro <nakamichiworks@gmail.com>",
]
homepage = "https://github.com/y-bar/netcleanser"
repository = "https://github.com/y-bar/netcleanser"
license = "MIT"
classifiers = [
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Topic :: Utilities",
]
include = [
    "LICENSE",
]

[tool.poetry.dependencies]
python = "^3.7"

purl = "^1.6"
requests = "^2.25.1"
tldextract = "^3.1.0"

[tool.poetry.dev-dependencies]
pytest = "^6.2.4"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
